### ISSUE TITLE
use with can0 in ubuntu

### ISSUE THREAD

**Issue by geppetto32** [han-xudong/CyberGear#1]
Hello Han Xuong , your library is very well structed and I've tried to make it work with can0 using capable 2.0. I am having a lot of trouble  with conversions to rads and to many errors as new in all that. Is it possible for you to provide a solution?It will be very appreciated.

**Comment by han-xudong** [comment]
Hi, thank you for your issue describing the trouble when using CANable 2.0. Yeah, as you mentioned, this library does not support CANable 2.0. Since the USB-to-CAN protocol strictly depends on the hardware, it's not available to use this library without the recommended DR USB-to-CAN adaptor, which can be bought on Taobao. 
Furthermore, maybe few months later, we will update the library to v1.0.0 which can support more adaptors including CANable 2.0.

**Comment by geppetto32** [comment]
thats good , thank you Han.
